from machine import Pin
from time import sleep
led1= Pin(23,Pin.OUT)
led2= Pin(22,Pin.OUT)
led3= Pin(21,Pin.OUT)
led4= Pin(33,Pin.OUT)
led5= Pin(25,Pin.OUT)
led6= Pin(26,Pin.OUT)
while True:
    led1.on()
    led3.on()
    led5.on()
    sleep(1)
    led1.off()
    led3.off()
    led5.off()
    sleep(1)
    led2.on()
    led4.on()
    led6.on()
    sleep(1)
    led2.off()
    led4.off()
    led6.off()
    sleep(1)
    print("Hello, Akash Singh")
